# Generated by Django 3.1.5 on 2021-03-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210318_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, default='nagar', max_length=50),
        ),
    ]
