# Generated by Django 3.1.5 on 2021-03-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210318_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='users',
            name='address2',
            field=models.CharField(blank=True, default='Address2', max_length=200),
        ),
    ]
